# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
   include:
     - '*'
  branches:
   include:
     - main

pool:
  vmImage: 'macOS-latest'

variables:
  phpVersion: 7.3

steps:
- script: composer install --no-interaction --prefer-dist
  displayName: 'Composer install'

- script: |
    curl -o- -L https://yarnpkg.com/install.sh | bash
    yarn install
    yarn encore dev
    yarn --version
  displayName: 'Install yarn'

- script: ./bin/phpunit
  displayName: 'Run tests with phpunit'

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(system.defaultWorkingDirectory)'
#    includeRootFolder: false
    
# - task: PublishBuildArtifacts@1